[book]
authors = [
  "Andika Demas Riyandi <andika.riyan@gmail.com>",
  "Jonas Chevalier <zimbatm@zimbatm.com>",
]
language = "en"
multilingual = false
src = "."
title = "treefmt â€” one CLI to format your repo"
